### ISSUE TITLE
New Feature: Update raffle state if all tickets are sold 

### ISSUE THREAD

**Issue by hard-nett** [AtlasDA0/app-contracts#11]

**Comment by hard-nett** [comment]
gonna have to work through what best choice to implement this may be. Few possibilities:
- call updateRandomness if no more tickets can be bought, so we can have a good randomness state modification.
- automation contracts: use available cosmwasm contracts to create cron jobs via 
- account abstraction: implement method to "have contract call itself"

**Comment by Jetblaster** [comment]
Automate randomness from Nois either after a raffle is over or the last ticket is sold. Whichever comes first.
