### ISSUE TITLE
New Feature: `multiple_winners`

### ISSUE THREAD

**Issue by hard-nett** [AtlasDA0/app-contracts#16]
Allow option to decide multiple winners

- `multiple_winners: Option<MultipleWinnerParams>` - optional parameter for raffles. 
- **MultipleWinnerParams:**
```rs
MultipleWinnerParams: {
num_winners: u64,
num_tokens_per_winner: u64, 
}
```

**Comment by Jetblaster** [comment]
Implement support to define the number of winners for a raffle if multiple assets are provided.
